# Setup
title:               Appmob tugas
tagline:             The Jekyll Companion
url:                 http://appmobgroub.github.io
analytics_id:        UA-53335201-2

# About/contact
author:
  name:                fheo18
  email:               "" # email here 
  avatar:              img/avatar.jpg 
  profile-pic:         img/profile-pic.jpg



# Build settings
markdown:            kramdown
permalink:           /:title
sass:
  sass_dir:          _sass
  style:            :compressed


# Default settings
defaults:
  -
    scope:
      path: "fheo18" 
      type: "posts" 
    values:
      layout: "post"
      author: Gabriel Utterson
  -
    scope:
      path: "fheo18" 
      type: "pages" 
    values:
      layout: "page"
      
